### ISSUE TITLE
Leftover `uid` styles during `--watch`/`--serve`

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-plugin-webc#17]
```html
<style @html="`#${uid} { --position: ${value}%; }`"></style>
```

Looks like those are sticking around even when the `uid` changes between builds

```css
#webc-q7gY8 { --position: 60%; }#webc-ehXEJ { --position: 60%; }#webc-CYrCA { --position: 60%; }#webc-lWwYc { --position: 60%; }#webc-P_AL3 { --position: 60%; }
```

Marginally related to #15
